### ISSUE TITLE
Print av tabeller sprer tekst med flere ord på flere linjer

### ISSUE THREAD

**Issue by anders-hammervold** [varianter/dokument-mal#13]
Det skjer ikke i web-visningen.

Eksempel:

https://avtaler.variant.no/avtaler/konsulentbistand-prismatrise.html?input-kunde=Kunde&input-signeringssted=Trondheim&input-signeringsdato=2019-08-31&input-kundens-ansvarlige-navn=Kundens+Navn&input-variants-ansvarlige-navn=Odd+Morten+Sve%C3%A5s&input-kundens-ansvarlige-stilling=Stilling&input-kundens-ansvarlige-telefon=815+49+300&input-kundens-ansvarlige-epost=kunde%40selskap.no&input-variants-ansvarlige-stilling=Daglig+leder&input-variants-ansvarlige-telefon=928+07+375%E2%80%AC&input-variants-ansvarlige-epost=oms%40variant.no&input-oppstartsdato=2019-01-29&input-avslutningsdato=2019-01-29&input-kunderepresentantens-navn=Kundens+Navn&input-kunderepresentantens-stilling=Stilling&input-kunderepresentantens-telefon=815+49+300&input-kunderepresentantens-epost=kunde%40selskap.no&input-variants-representant-navn=Odd+Morten+Sve%C3%A5s&input-variants-representant-stilling=Daglig+leder&input-variants-representant-telefon=928+07+375%E2%80%AC&input-variants-representant-epost=oms%40variant.no&input-timeprisrabatt-tittel=Rabattert+%28*%29&input-kategori-1=Juniorkonsulent&input-timepris-1a=900&input-timepris-1b=850&input-kategori-2=Konsulent&input-timepris-2a=1050&input-timepris-2b=1000&input-kategori-3=Seniorkonsulent&input-timepris-3a=1200&input-timepris-3b=1150&input-kategori-4=Ekspert&input-timepris-4a=1350&input-timepris-4b=1290&input-timeprisrabatt-beskrivelse=%28*%29+Rabattert+timesats+gjelder+oppdrag+med+varighet+lengre+enn+6+mnd.&input-faktura-betalingstid=15+%28femten%29&input-fakturamerknad-refnr=Kundes+refnr&input-fakturamerknad-navn=Kundens+Navn&input-fakturamerknad-epost=kunde%40selskap.no&input-overdragelse-samtykke=Samtykke+kan+ikke+nektes+uten+saklig+grunn.&input-n-kkelpersonell%5B0%5D%5Bnavn%5D=Konsulent+Konsulentesen&input-n-kkelpersonell%5B0%5D%5Bkategori%5D=Kategori+Kategoriene&input-n-kkelpersonell%5B0%5D%5Bstilling%5D=Stilling+Stillingene

**Comment by mikaelbr** [comment]
Takk! Digger at vi kan reprodusere feil via state i URL på denne måten. Gjør det så mye enklere å fikse.
