### ISSUE TITLE
Skjemaet viser bare en konsulent. skal være to. 

### ISSUE THREAD

**Issue by oddsve** [varianter/dokument-mal#15]
https://avtaler.variant.no/avtaler/enkel-konsulentbistand.html?input-kunde=Powel&input-signeringssted=Trondheim&input-signeringsdato=2019-06-11&input-kunderepresentantens-navn=Jens+Evensen&input-kunderepresentantens-stilling=Leder&input-kunderepresentantens-telefon=555+55+555&input-kunderepresentantens-epost=jens%40evensen.com&input-beskrivelse-av-bistand=Designbistandl&input-oppstartsdato=2019-06-01&input-avslutningsdato=2019-07-31&input-timepris-seniorkonsulent=1+400&input-timepris-konsulent=1+240&input-timepris-juniorkonsulent=1+050&input-betalingsutsettelse=15&input-kundes-refnr=Kundes+refnr&input-n-kkelpersonell%5B0%5D%5Bnavn%5D=Tonje+Evanger&input-n-kkelpersonell%5B0%5D%5Bstilling%5D=Seniorkonsulent&input-n-kkelpersonell%5B2%5D%5Bnavn%5D=Magnus+S%C3%A6ther&input-n-kkelpersonell%5B2%5D%5Bstilling%5D=Konsulent

Avtalen er riktig

**Comment by mikaelbr** [comment]
Dette skal være fikset nå.
