### ISSUE TITLE
utskrift uten default topp og bunn-tekst

### ISSUE THREAD

**Issue by oddsve** [varianter/dokument-mal#3]
Altså uten den som kommer standard

**Comment by mikaelbr** [comment]
Tror vi rett og slett må overlate det til nettleseren. Har prøvd alt for lenge, men det viser seg at nettlesere ikke har implementert støtte for dette enda.

F.eks i Chrome kan man gjøre:

<img width="328" alt="screenshot 2019-02-07 at 23 07 21" src="https://user-images.githubusercontent.com/606374/52446059-3426ee00-2b2d-11e9-8772-56c9f74d8f2f.png">
